# Change these first
owner: iamenews # Your GitHub organization or username, where this repository lives
repo: wiki-uptime # The name of this repository

sites:
  - name: Wiki Site
    url: https://dovedale.wiki/load.php
    method: GET
    maxResponseTime: 2000
    assignees:
      - jaiden-04
  - name: Dovedale Assistant Bot
    url: http://kairi.tokyo/
    icon: https://camo.githubusercontent.com/a0eebdbc73e0f4b7ceaa45a39f72d53c92c7960bb3312868d8f6125ae13aeb79/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f617661746172732f313232393439393631373534393438343137342f35393162343864386566313461646631356235306438346536316363353563372e776562703f73697a653d3830
    maxResponseTime: 20000
    assignees:
      - kairijp
  - name: Dovedale Webhook Proxy
    url: https://webhook.dovedale.wiki/
    icon: https://webhook.dovedale.wiki/img/logo.svg
    maxResponseTime: 2000
    assignees:
      - jaiden-04
  - name: Dovedale Roblox Joiner
    url: https://join.dovedale.wiki/
    icon: https://i.ibb.co/B5TvJmTd/logo-1.png
    maxResponseTime: 2000
    assignees:
      - jaiden-04
  - name: Dovedale Live Map
    url: https://map.dovedale.wiki/
    maxResponseTime: 2000
    assignees:
      - jaiden-04

status-website:
  theme: night
  cname: status.dovedale.wiki
  logoUrl: https://raw.githubusercontent.com/iamenews/wiki-uptime/40ec76472a04b008822a556f4f1c2cd1a91e1cf7/assets/sadcomputer.png
  name: Dovedale Wiki Statuspage
  introTitle: Dovedale Wiki Uptime 
  introMessage: Having issues? Check out if its just you, or if its us. 
  customHeadHtml: <script async defer src="https://check.dovedale.wiki/latest.js"></script> 
  navbar:
    - title: Wiki
      href: https://dovedale.wiki
    - title: Play
      href: roblox://placeId=12018816388/
    - title: Repository
      href: https://github.com/iamenews/wiki-uptime/
    - title: Discord
      href: https://discord.gg/hmqCYg4P23
      
i18n:
  footer: By The Dovedale Wiki & Dev Team 🐈  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
