# Change these first
owner: iamenews # Your GitHub organization or username, where this repository lives
repo: wiki-uptime # The name of this repository

sites:

status-website:
  theme: night
  cname: status.dovedale.wiki
  logoUrl: https://raw.githubusercontent.com/iamenews/wiki-uptime/40ec76472a04b008822a556f4f1c2cd1a91e1cf7/assets/sadcomputer.png
  name: Dovedale Wiki Statuspage
  introTitle: Dovedale Wiki Uptime 
  introMessage: Having issues? Check out if its just you, or if its us. 
  customHeadHtml: <script async defer src="https://check.dovedale.wiki/latest.js"></script> 
  navbar:
    - title: Wiki
      href: https://dovedale.wiki
    - title: Play
      href: roblox://placeId=12018816388/
    - title: Repository
      href: https://github.com/iamenews/wiki-uptime/
    - title: Discord
      href: https://discord.gg/hmqCYg4P23
      
i18n:
  footer: By The Dovedale Wiki & Dev Team 🐈  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
