# Change these first
owner: iamenews # Your GitHub organization or username, where this repository lives
repo: wiki-uptime # The name of this repository

sites:
  - name: Wiki Site
    url: https://dovedale.wiki
  - name: Roblox service
    url: https://roblox.com

status-website:
  theme: night
  cname: status.dovedale.wiki
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Here you can view **live** status updates about Dovedale services."
  introMessage: Please if any downtime occurs notify a staff member on our discord. (discord.gg/dovedale)
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://dovedale.wiki
    - title: Play
      href: roblox://placeId=12018816388/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
