# Change these first
owner: iamenews # Your GitHub organization or username, where this repository lives
repo: wiki-uptime # The name of this repository

sites:
  - name: Wiki Site
    url: https://dovedale.wiki

status-website:
  theme: night
  cname: status.dovedale.wiki
  logoUrl: https://ibb.co/2MQK2kj
  name: Dovedale Wiki Statuspage
  introTitle: Dovedale Wiki Uptime 
  introMessage: Having issues? Check out if its just you, or if its us. 
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://dovedale.wiki
    - title: Play
      href: roblox://placeId=12018816388/
      
i18n:
  footer: By The Dovedale Wiki Team 
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
